team48-22-main/team48-22-main/app/reeltravel/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    url(r"^", include('homepage.urls')),
    url(r"^", include('users.urls')),
    url(r"^", include('plainmap.urls')),
    url(r"^",include('search.urls')),
    path('admin/', admin.site.urls),

]

team48-22-main/team48-22-main/app/search/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('search_index/',views.search_index,name='search_index'),
    path('listview/', views.IndexView.as_view(), name='starting'),
    path('searchmovies/', views.searchmovies, name="searchmovies"),
    path('globe/', views.globe, name='globe'),
    path('moviedetails/', views.moviedetails, name="moviedetails"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

team48-22-main/team48-22-main/app/users/urls.py
from django.urls import path
from django.conf.urls import include, url
from users.views import dashboard,login_register,confirm_email


urlpatterns = [
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^dashboard/", dashboard, name="dashboard"),
    path('password-reset/', include('password_reset.urls')),
    path('login_register/', login_register, name='login_register'),
    path('confirm-email/<str:uidb64>/<str:token>/', confirm_email, name='confirm_email'),
]

team48-22-main/team48-22-main/app/search/models.py
from django.db import models

# Create your models here.

from django.db import models
from django.contrib.auth.models import User


class Genre(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Actor(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Director(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Location(models.Model):
    name = models.CharField(max_length=255)
    coordinates = models.TextField(default=None, blank=True)
    #coordinates = models.TextField()
    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    release_date = models.DateField()
    genres = models.ManyToManyField(Genre)
    actors = models.ManyToManyField(Actor)
    director = models.ManyToManyField(Director)
    locations = models.ManyToManyField(Location)

    class Meta:
        ordering=('title',)
        verbose_name_plural="movies"

    def __str__(self):
        return self.title


class MoviePhoto(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='movie_photos/')

    def __str__(self):
        return f"Photo for location {self.movie.title}"


class LocationPhoto(models.Model):
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='location_photos/')

    def __str__(self):
        return f"Photo for location {self.location.name}"


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.IntegerField()
    profile_picture = models.ImageField(upload_to='users/', default='default.png')

    def __str__(self):
        return self.user.username


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    text = models.TextField()
    rating = models.IntegerField()

    def __str__(self):
        return self.text


class ReviewPhoto(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='review_photos/')

    def __str__(self):
        return f"Photo for review {self.review.id}"

team48-22-main/team48-22-main/app/search/views.py
from django.shortcuts import render
from .models import Movie, Review, ReviewPhoto
from django.views.generic import ListView, DetailView
from django.http import QueryDict, HttpResponse

# Create your views here.

class IndexView(ListView):
    model = Movie
    template_name = 'search_index.html'
    queryset=Movie.objects.all()
    context_object_name= 'posts'

def search_index(request):
    return render(request, 'search_index.html', {})

def searchmovies(request):
    if request.method=="POST":
        wordtosearch=request.POST.get('wordtosearch', False)
        sitename = wordtosearch+"- List Search"
        movies = Movie.objects.filter(title__contains=wordtosearch)
        length = movies.count()
        return render(request, 'searchmovies.html', {'wordtosearch':wordtosearch, 'movies':movies, 'length':length, 'sitename':sitename})
    else :
        return render(request, 'searchmovies.html', {})
    
def moviedetails(request):
    query = request.GET.get('q')
    if query:
        movies = Movie.objects.filter(title__icontains=query)
        if movies.exists():
            movie = movies.first()
            reviews = Review.objects.filter(movie=movie)
            review_photos = {}
            for review in reviews:
                review_photos[review.id] = ReviewPhoto.objects.filter(review=review)
            return render(request, 'searchdetails.html', {'movie': movie, 'reviews': reviews, 'review_photos': review_photos})
    return render(request, 'searchdetails.html', {})    

def globe(request):
    return render(request, 'globe.html', {'sitename': 'globe'})

def searchmoviescss(request):
    css_contents="""
        .results{
            margin: 50px;
        }

        .clickable{
            background-color: #1c87c9;
            border: none;
            color: white;
            padding: 20px 34px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 20px;
            margin: 4px 2px;
            cursor: pointer;
        }
        
    """
    response=HttpResponse(css_contents, content_type="text/css")
    return response

team48-22-main/team48-22-main/app/search/templates/basesearch.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

team48-22-main/team48-22-main/app/search/templates/globe.html
{% load custom_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>3DEarth</title>
</head>
<body>
    <p>COMING SOON</p>
</body>
</html>

team48-22-main/team48-22-main/app/search/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>Welcome to movie search</p>
    <form method=POST action="{% url 'searchmovies' %}">
        {% csrf_token %}
        <input type="search" placeholder="Search For Movies" aria-label="wordtosearch" name="wordtosearch">
        <button type="submit">Search</button>
    </form>
</body>
</html>

team48-22-main/team48-22-main/app/search/templates/search_index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
#container{

    height: 300px;
}
</style>
     <div class="crumbs">
        <ul>
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="#">Search </a></li>
        </ul>
    </div>
<section id="container">
			<div class="wrap-container">
    <p>Welcome to movie search</p>
    <form method=POST action="{% url 'searchmovies' %}">
        {% csrf_token %}
        <input type="search" placeholder="Search For Movies" aria-label="wordtosearch" name="wordtosearch">
        <button type="submit">Search</button>
    </form>
            </div>
</section>
 {% endblock %}

team48-22-main/team48-22-main/app/search/templates/searchdetails.html
{% extends "basesearch.html" %}
{% load custom_tags %}
{% block title %}{{movie.title}}- Details{% endblock %}
{% block head %}
<style>
    body{
        text-align: center;
        background-color: white;
        color: black;
        font-size: 16px;
        font-family: "Segoe UI", serif;
    }

    .darktheme{
        text-align: center;
        background-color: #19037a;
        color: white;
    }

    #intro1{
        width: 8%;
    }

    .largefont{
        font-size: 24px;
    }

    .firstdiv1{
        width: 18%;
        display: inline-block;
    }

    .firstdiv2{
        width: 13%;
        display: inline-block;
    }

    .bar{
        width: 19%;
        float: right;
    }

    .firstdiv3{
        display: inline-block;
        width: 8%;
    }

    #imagesee{
        float: right;
    }

    .movieinfo{
        border-style: solid;
        border-left-color: white;
        border-right-color: white;
        border-top-color: #ee00ff;
        border-bottom-color: #ee00ff;
        width: 80%;
        float: left;
    }

    .movieinfodark{
        border-color: #ee00ff;
    }

    .maindev{
        display: flex;
    }

    .pleft{
        float: left;
        text-align: left;
        width: 80%;
    }

    #pleft2{
        float: left;
        
    }

</style>
{% endblock %}

{% block content %}


<form method="get">
    <input type="text" name="q" placeholder="Search specific movies" value="{{ request.GET.q }}">
    <button type="submit">Search</button>
</form>

{% if movie %}
<div class="maindiv">
    <h2>{{movie.title}}</h2>

    <div class="movieinfo">
        <div class="pleft">
            <h2>Introduction</h2>
            <p>{{movie.description}}</p>
            <h2>Release date</h2>
            <p>{{movie.release_date}}</p>
            <h2>Movie Genres</h2>
            <div>
                {% for genre in movie.genres.all %}
                    {{ genre.name }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </div>
            <h2>Actors</h2>
            <div>
                {% for actor in movie.actors.all %}
                    {{ actor.name }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
                 and more
            </div>
            <h2>Directors</h2>
            <div>
                {% for director in movie.director.all %}
                    {{ director.name }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </div>
            <h2>Known filming locations</h2>
            <div>
                {% for location in movie.locations.all %} <!--temporary change locations to location (reverted)-->
                    <h3>{{ location.name }}</h3>
                    {% for photo in location.locationphoto_set.all %}
                        <img src="{{ photo.image.url }}" alt="Location Photo" width="200">
                    {% endfor %}
                {% endfor %}
            </div>
            <h2>Current reviews</h2>
            {% if reviews %}
                {% for review in reviews %}
                <div>
                    <h3>{{ review.user.username }}, {{ review.rating }}</h3>
                    <p>{{ review.text }}</p>
                    {% for photo in review_photos|get_item:review.id %}
                        <!--| get_item:review.id -->
                        <img src="{{ photo.image.url }}" alt="Review Photo" width="100">
                    {% endfor %}
                </div>
                {% endfor %}
            {% else %}
                <p>
                    currently no reviews available for this movie.
                </p>
            {% endif %}
            
        </div>
        {% for photo in movie.moviephoto_set.all %}
            <img src="{{ photo.image.url }}" alt="Movie Photo" width="200" id="imagesee">
        {% endfor %}
        
    </div>
</div>
{% else %}
    <p>Unfortunately, No movie found related to the search term.</p>
{% endif %}

<div class="bar">
    <div class="firstdiv2"><button id="darklight" onclick="adjustlight()">Light/Dark</button></div>
    <br>
    <div class="firstdiv3"><button id="fontlarge" onclick="adjustfont()">a/A</button></div>
</div>

</div>



<script>
    function adjustlight(){
        var element= document.body;
        element.classList.toggle("darktheme");
    }

    function adjustfont(){
        var element=document.body;
        element.classList.toggle("largefont");
    }
</script>

{% endblock %}

team48-22-main/team48-22-main/app/search/templates/searchmovies.html
{% extends "base.html" %}

{% block title %}{{sitename}}{% endblock %}
{% block head %}
    <style>
        body{
            font-family: "Segoe UI";
            background-color: white;
            color: black;
            font-size: 20px;
        }

        .darktheme{
            background-color: #19037a;
            color: white;
        }

        #descriptions{
            max-height: 53px;
            width: 70%;
            overflow: hidden;
        }

        .results{
            display: inline-block;
            width: 15%;
        }

        .clickable{
            background-color: #1c87c9;
            cursor: pointer;
        }

        .nearbyresults{
            display: inline-block;
            width: 50%;
            margin-left: 4%;
            max-height: 20px;
            position: absolute;
            vertical-align: top;
        }

        #searchingmovie{
            font-family: "Segoe UI";
        }

        #buttonsubmit{
            font-family: "Segoe UI"
        }

        #h1resultstag{
            font-family: "Segoe UI"
        }

        p{
            font-family: "Segoe UI"
        }

        .bigdiv{
            width: 49%;
            display: inline-block;
            border-style: solid;
            margin-bottom: 13px;
            min-height: 200px;
        }

        #buttondetails{
            vertical-align: bottom;
            position: absolute;
            margin-left: 8%;
        }

        #images{
            max-height: 200px;
            max-width: 160px;
            overflow: hidden;
        }

        #disclaimer1{
            font-size: 14px;
        }

        .themes{
            display: inline-block;
        }

        .enlarge{
            font-size: 28px;
        }

    </style>
{% endblock %}
{% block content %}
     <div class="crumbs">
        <ul>
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="#">Search </a></li>
            <li><a href="#">Search Results</a></li>
        </ul>
    </div>
    <form method=POST action="{% url 'searchmovies' %}">
        {% csrf_token %}
        <input type="search" placeholder="Search For Movies" aria-label="wordtosearch" name="wordtosearch" id="searchingmovie">
        <button type="submit" id="buttonsubmit">Search</button>
    </form>
    <div class="themes">
        <button id="darking" onclick="darktheme()">Light/Dark</button>
        <button id="enlarge" onclick="enlarging()">a/A</button>
    </div>
    {% if wordtosearch %}
        {% if length > 0 %}
            <h1 id="h1resultstag">Results for searching movies containing "{{ wordtosearch }}":</h1>
            <br>
            
            {% for movie in movies %}
            <div class="bigdiv">
                <div class="results">
                    {% for photo in movie.moviephoto_set.all %}
                        <img src="{{ photo.image.url }}" alt="Movie Photo" id="images">
                    {% endfor %}
                </div>
                <div class="nearbyresults">
                    <p>{{movie.title}}</p>
                    <p id="descriptions">{{movie.description}}</p>
                </div>
                <button onclick="location.href='/moviedetails?q={{movie.title}}'" id="buttondetails">Details</button>
            </div>    
            {% endfor %}
        {% else %}
            <h1>No results found or no input received</h1>
        {% endif %}
    {% else %}
        <h1>No results found or no input received</h1>
    {% endif %}
        <br>
            <script>
            function darktheme(){
                var element= document.body;
                element.classList.toggle("darktheme");
            }

            function enlarging(){
                var element=document.body;
                element.classList.toggle("enlarge");
            }

        </script>

{% endblock %}